/**:
  ros__parameters:
    input: tcp_file
    policy: focus
    tcp_control_mode: feature
    tcp_host: 127.0.0.1
    tcp_port: 1234
    file_path: tcp_data.txt
    lsl_stream_type: EEG
    lsl_timeout: 8.0
    lsl_channel_map: alpha=0,theta=1,beta=2,left_alpha=3,right_alpha=4
    cmd_topic: /cmd_vel
    analysis_topic: /eeg_analysis
    publish_hz: 20.0
    watchdog_sec: 0.5
    verbose: false
    analysis_verbose: false
    record_csv: false
    csv_path: /tmp/thymio_eeg_log.csv
    max_forward_speed: 0.2
    reverse_speed: -0.15
    turn_forward_speed: 0.1
    turn_angular_speed: 1.2
    reverse_threshold: 0.2
    steer_deadzone: 0.1
    line_mode: ''
