- ros_topic_name: /model/thymio/cmd_vel
  gz_topic_name: /model/thymio/cmd_vel
  ros_type_name: geometry_msgs/msg/Twist
  gz_type_name: gz.msgs.Twist
  direction: BIDIRECTIONAL
  lazy: false

- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: /odom
  gz_topic_name: /model/thymio/odometry
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: gz.msgs.Odometry
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: /tf
  gz_topic_name: /model/thymio/tf
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: gz.msgs.Pose_V
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: /ground/left
  gz_topic_name: /model/thymio/ground_left
  ros_type_name: sensor_msgs/msg/Range
  gz_type_name: gz.msgs.LaserScan
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: /ground/right
  gz_topic_name: /model/thymio/ground_right
  ros_type_name: sensor_msgs/msg/Range
  gz_type_name: gz.msgs.LaserScan
  direction: GZ_TO_ROS
  lazy: false