use_sim: true
use_gui: false
run_eeg: false
run_gaze: false
run_rviz: false
use_teleop: true
use_tobii_bridge: false
use_enobio_bridge: false
tobii_udp_port: 5005
enobio_udp_port: 5006
eeg_config_file: eeg_control_node.params.yaml
gaze_config_file: gaze_control_node.params.yaml
